// Generated by https://quicktype.io

export interface ICategoriesResponse {
  trivia_categories: ITriviaCategory[];
}

export interface ITriviaCategory {
  id: number;
  name: string;
}
// Generated by https://quicktype.io

export interface IQuizQuestionResponse {
  response_code: number;
  results: IQuizQuestion[];
}

export interface IQuizQuestion {
  category: string;
  type: Type;
  difficulty: Difficulty;
  question: string;
  correct_answer: string;
  incorrect_answers: string[];
}

export enum Difficulty {
  Easy = 'easy',
  Hard = 'hard',
  Medium = 'medium',
}

export enum Type {
  Boolean = 'boolean',
  Multiple = 'multiple',
}
